### ISSUE TITLE
Error: No file called render_balls_so

### ISSUE THREAD

**Issue by luotuoqingshan** [val-iisc/densepcr#5]
Hi,

Thank you for open sourcing the code. It's a good work.

When running the code, I went into a problem. I ran `python show3d_balls.py` and got an error.
```
Traceback (most recent call last):
  File "show3d_balls.py", line 20, in <module>
    dll=np.ctypeslib.load_library('utils/visualization/render_balls_so','.')
  File "/anaconda3/lib/python3.6/site-packages/numpy/ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
```
It seems that you forget one file?

**Comment by jessiuss** [comment]
I have the same question. Can anyone answer it?thank you
